services:
  nextjs:
    build: .
    container_name: papodebola-next
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - pdb-data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

volumes:
  pdb-data:
