services:
  nextjs:
    build: .
    container_name: papodebola-next
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - ./data:/app/data
    networks:
      - default
